### ISSUE TITLE
how to install SSL certificate?

### ISSUE THREAD

**Issue by Eilaluth** [akbaryahya/DockerGC#16]
well i've been struggling with SSL issues cuz i have little experience with docker, so the case is i don't know this docker script running on nginx or apache 2 and i don't have both installed  in my ubuntu vps so i though docker is running http by itself but then i wonder how can i install the SSL certificate cuz all the tutorial on google using nginx.

sorry but it would be really helpful if you tell me how to do it thanks.

**Comment by akbaryahya** [comment]
You can use this https://nginxproxymanager.com/setup/ and just use https://github.com/akbaryahya/DockerGC/blob/main/docker-compose_public.yml

**Comment by Elliottophellia** [comment]
i've been trying to use https://github.com/akbaryahya/DockerGC/blob/main/docker-compose_public.yml for 2 days now but it's always return error (ERR_EMPTY_RESPONSE) in port 443, probably because nginx proxy manager uses 443 but i have no idea, been trying with 443 disabled for nginx proxy manager but the SSL seems not work

**Comment by akbaryahya** [comment]
You have to setup proxy inside nginx proxy manager not outside https://www.youtube.com/watch?v=h1a4u72o-64
